### ISSUE TITLE
On linux the everything mode works but packing and hovering dont

### ISSUE THREAD

**Issue by katSchmid** [MiscellaneousStuff/meta-sam-demo#14]
On my local linux machine the everything mode works but packing and hovering dont. I can set a dot on the image, undo and reset wont work either.
Is the backend different between everything and the other modes?

App.tsx:119 Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #41 module="a" function="P" error: function import requires a callable). Build with -sASSERTIONS for more info., [cpu] Error: previous call to 'initializeWebAssembly()' failed., [xnnpack] Error: previous call to 'initializeWebAssembly()' failed.
    at backend-impl.js:87:1
    at async d.create (inference-session-impl.js:169:1)
    at async initModel (App.tsx:115:1)

**Comment by ericsvendsen** [comment]
Sounds like maybe the answer to this could be similar to [my response](https://github.com/MiscellaneousStuff/meta-sam-demo/issues/10#issuecomment-1579346740) to #10?

**Comment by katSchmid** [comment]
"onnxruntime-common": "^1.14.0",
 "onnxruntime-web": "^1.14.0", doesnt look like it?

Is it using the endpoint for all mode ?
    const allRequest =
      imgName && !shouldDownload
        ? fetch(`/assets/gallery/${allImgName}.txt`)
        : fetch(`${ALL_MASK_API_ENDPOINT}`, {
            method: "POST",
            body: blob,
          });

**Comment by 3a1b2c3** [comment]
Same error and result on my windows machine in local mode.  packing === picking

**Comment by qxx861305133** [comment]
![image](https://github.com/MiscellaneousStuff/meta-sam-demo/assets/31298057/9c33cfeb-0bd9-4d4a-9b3e-26450413c63c)
![image](https://github.com/MiscellaneousStuff/meta-sam-demo/assets/31298057/51367d49-8369-430d-9c15-62815042f20d)
why?
